version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      KC_SPI_EVENTS_LISTENER_USER_UPDATE_WEBHOOK_URLS: "http://watcher:3000/api"
    ports:
      - "8080:8080" # keycloak
    command:
      - start-dev
    volumes:
      - ./target:/opt/keycloak/providers
